apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  # pod definition
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        # replace with your pushed image or just use mine
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
