# Service
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    run: hello-world
    subdomain: hello-world
spec:
  type: NodePort
  ports:
  - port: 80 # port to serve service on
    targetPort: 8080 # containers port
    protocol: TCP
  selector:
    app: hello-world
  # sessionAffinity: ClientIP

# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  # pod definition
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        # replace with your pushed image or just use mine
        image: esayemm/hello-world:0.2.4
        ports:
        - containerPort: 8080
