# Service
apiVersion: v1
kind: Service
metadata:
  name: hello-universe
  labels:
    run: hello-universe
    subdomain: hello-universe
spec:
  type: NodePort
  ports:
  - port: 80 # port to serve service on
    targetPort: 8080 # containers port
    protocol: TCP
  selector:
    app: hello-universe
  # sessionAffinity: ClientIP

---

# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-universe
spec:
  replicas: 1
  # pod definition
  template:
    metadata:
      labels:
        app: hello-universe
    spec:
      containers:
      - name: hello-universe
        # replace with your pushed image or just use mine
        image: esayemm/hello-universe:0.1.1
        ports:
        - containerPort: 8080
